name: rankify
description: "Rankify is an AI designed to help brawl stars players reach higher ranks by providing them hidden and niche brawler picks."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.0+3

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  http: ^1.6.0
  tflite_web: ^0.4.0
  wolkarutils:
    git:
      url: "https://github.com/wolkar-dev/wolkarutils.git"
  audioplayers: ^6.6.0
  speech_to_text: ^7.3.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
  - assets/sounds/
  - assets/fonts/
  - assets/data/
  - assets/models/
  - assets/icons/
  - assets/images/
  - assets/images/app/

  fonts:
  - family: "Outfit"
    fonts:
    - asset: "assets/fonts/regular.ttf"
      weight: 500
    - asset: "assets/fonts/semi.ttf"
      weight: 600
    - asset: "assets/fonts/bold.ttf"
      weight: 700
