#    Rankify is an Open Source AI app made to help brawl stars players reach higher ranks.
#    Copyright (C) 2026 WoLKaR-dev
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see https://www.gnu.org/licenses/

name: Data gather
on: 
  schedule:
    - cron: 0 */6 * * * # each 6h
  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      #
      # Gets the repo data. 
      #
      - name: Getting repo info
        uses: actions/checkout@v4
        
        with:
          ref: gather 
          token: ${{ secrets.GITHUB_TOKEN }} # get last repo data from gather branch
      
      #
      # Install python. 
      #
      - name: Installing python
        uses: actions/setup-python@v5
        with: 
          python-version : '3.10' # installing python

      #
      # Install dependencies. 
      #
      - name: Installing dependencies # installing dependencies for data gathering
        run: |
          pip install -r requirements.txt 
        
      #
      # Execute gather script. 
      #
      - name: Executing gather # execute script
        run: python3 data_gather.py
        env: 
          BS_API_KEY: ${{ secrets.BS_API_KEY }} # in your repo, add BS_API_KEY secret with your brawl stars api key value

      #
      # Add data to release.
      #
      - name: Upload Gathered Data Artifact # upload gathered data
        uses: actions/upload-artifact@v4
        with: 
          name: gathered-data
          path: |
            matches.csv
            affinity.csv
            counter.csv

      #
      # Release public data
      #
      - name: Release data # release gathered data
        uses: softprops/action-gh-release@v2
        with: 
          tag_name: latest-data
          name: "Latest Data"
          body: |
            This release is updated hourly. 
            Last sync: ${{ github.event.repository.updated_at }}
          files: |
            matches.csv
            affinity.csv
            counter.csv
          make_latest: true
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #
      # Add JSONs and models to branch. 
      #
      - name: Add data to branch # add new data to branch
        run: |
          git config --global user.name "Auto Gather"
          git config --global user.email "action@github.com"
          git add . 
          git commit -m "New data added"
          git push
      
