#    Rankify is an Open Source AI app made to help brawl stars players reach higher ranks.
#    Copyright (C) 2026 WoLKaR-dev
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see https://www.gnu.org/licenses/

name: Train Model

on: 
  workflow_dispatch:
  workflow_run: 
    workflows: ["Data gather"]
    types:
      - completed

jobs: 
  train: 
    runs-on: ubuntu-latest
    steps:

      #
      # Checkout code
      #
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: gather 
          token: ${{ secrets.GIT_TOKEN }} 


      #
      # Install python
      #
      - name: Install python
        uses: actions/setup-python@v5
        with: 
          python-version : '3.10' 
        
      #
      # Install Kaggle CLI
      # 
      - name: Installing Kaggle CLI
        run: pip install kaggle


      #
      # Create new folder and connect to kaggle. 
      #          
      - name: Connecting to Kaggle
        run: |
          mkdir -p ~/.kaggle 
          echo "${{ secrets.KAGGLE_ACCESS_TOKEN }}" > ~/.kaggle/access_token 
          chmod 600 ~/.kaggle/access_token
          
          mkdir -p kaggle_data
          cp matches.csv.gz kaggle_data/

          echo '{"id" : "wolkar/matches"}' > kaggle_data/dataset-metadata.json
      #
      # Send data to Kaggle
      #
      - name: Sending data to Kaggle 
        run: |
          kaggle datasets version -p kaggle_data -m "Update matches data"
        env:
          KAGGLE_USERNAME: "wolkar"
          KAGGLE_KEY: ${{ secrets.KAGGLE_ACCESS_TOKEN }}

      #
      # Pulling and running notebook
      #
      - name: Pulling and running notebook # pull and run notebook to update data on kaggle
        run: |
          kaggle kernels pull wolkar/rankify -p ./.run_dir --metadata
          
          # Hacemos el push apuntando directamente a la carpeta sin movernos de la raíz
          # Usamos '|| true' por si la CLI da error de streaming al principio
          kaggle kernels push -p ./.run_dir || true
          
          echo "Waiting for notebook to finish running..."
          sleep 15
          
          while true; do
           
            RAW_STATUS=$(kaggle kernels status wolkar/rankify || echo "KAGGLE_API_ERROR")
            echo "Raw response: $RAW_STATUS"
          
            if echo "$RAW_STATUS" | grep -iq "KAGGLE_API_ERROR"; then
              echo "La API de Kaggle no respondió correctamente o está saturada. Reintentando..."
            
            elif echo "$RAW_STATUS" | grep -iq "Unauthenticated"; then
              echo "Error crítico: Las credenciales de Kaggle fallaron."
              exit 1
            
            elif echo "$RAW_STATUS" | grep -iq "COMPLETE"; then
              echo "¡Notebook finalizado con éxito!"
              break
            
            elif echo "$RAW_STATUS" | grep -iqE "ERROR|CANCELLED"; then
              echo "Error real: El notebook ha fallado o fue cancelado en Kaggle."
              exit 1
              
            else
              echo "El notebook sigue procesándose en Kaggle..."
            fi
          
            echo "Esperando 30 segundos..."
            sleep 30
          done
          
          echo "Descargando resultados..."
          kaggle kernels output wolkar/rankify -p ./results/
        env:
          KAGGLE_USERNAME: "wolkar"
          KAGGLE_KEY: ${{ secrets.KAGGLE_ACCESS_TOKEN }}

      #
      # Add JSONs and models to branch. 
      #
      - name: Add data to branch # add new data to branch
        run: |
          cp ./results/draft_model.tflite ./
          cp ./results/brawler_mapping.json ./
          cp ./results/map_mapping.json ./

          rm -rf ./.run_dir
          rm -rf ./kaggle_data
          rm -rf ./results

          git config --global user.name "Auto Gather"
          git config --global user.email "action@github.com"
          git add . 
          git commit -m "New data added and model trained"
          git push
      
      #
      # Add data to release.
      #
      - name: Upload Gathered Data Artifact # upload gathered data
        uses: actions/upload-artifact@v4
        with: 
          name: trained-model-&-data
          path: |
            brawler_mapping.json
            map_mapping.json
            draft_model.tflite

      #
      # Release public data
      #
      - name: Release data # release gathered data
        uses: softprops/action-gh-release@v2
        with: 
          tag_name: latest-model-data
          name: "Latest Model and Data"
          body: |
            This release is updated hourly. 
            Last sync: ${{ github.event.repository.updated_at }}
          files: |
            brawler_mapping.json
            map_mapping.json
            draft_model.tflite
          make_latest: true
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #
      # Do checkout on daily
      #
      - name: Daily Checkout
        uses: actions/checkout@v4
        with:
          ref: daily 
          token: ${{ secrets.GITHUB_TOKEN }}

      #
      # Obtain data from the release 
      #
      - name: Obtain data from release # obtain new data from release
        run: |
          gh release download latest-model-data --pattern "*.json" --dir ./assets/data --clobber
          gh release download latest-model-data --pattern "*.tflite" --dir ./assets/models --clobber
          git add . 
          git commit -m "New model and data added"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}